
spring:
  application:
    name: eureka-discovery-service

server:
   port: 8585

eureka:
   client:
      registerWithEureka: false
      fetchRegistry: false
      serviceUrl: 
        defaultZone: http://localhost:8585/eureka
        
